version: "3"
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules # Use the node_modules inside the container
      - .:/app # Map the curr working dir to the /app folder inside the container
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["pnpm", "test"] # Override the default command