name: Deploy Frontend

on:
  push:
    branches: ["master"]
  pull_request: 
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build the Docker image
        run: docker build -f Dockerfile.dev -t aelzawawy/docker-react .

      - name: Run the Docker tests
        run: docker run -e CI=true aelzawawy/docker-react pnpm test
      
      # Since Nginx won't run in GitHub Pages,
      # Just copy the built static files from a temp container
      # to './build' on the GitHub Actions runner's filesystem
      - name: Build for production
        run: |
          docker build -t aelzawawy/frontend-prod .
          CONTAINER_ID=$(docker create aelzawawy/frontend-prod)
          docker cp $CONTAINER_ID:/usr/share/nginx/html ./build
          docker rm $CONTAINER_ID